version: '3'

services:

    activemq:
      image: rmohr/activemq:latest
      container_name: activemq
      environment:
        - "TZ=Europe/Amsterdam"
      volumes:
        - "./activemq/activemq.xml:/conf/activemq.xml"
      ports:
        - "61616:61616"
        - "8161:8161" 
    postgres:
      image: postgres:14.2-alpine
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=chat
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - PGDATA=/data
      command: [ "postgres", "-c", "log_statement=all" ]
      # volumes:
      #  - ./data:/data
